### ISSUE TITLE
500 Internal eError for Custom Award Bulk Download

### ISSUE THREAD

**Issue by apollo06** [fedspendingtransparency/usaspending-api#1196]
Hello,

I was trying to use the Custom Award Bulk Download, but kept getting 500 error. Not sure what I have done wrong. Any idea?

![image](https://user-images.githubusercontent.com/6812012/38751378-ed05d674-3f25-11e8-93eb-e7d4f4e64c2a.png)

**Comment by lisaam** [comment]
Try one year or less of data, not 54 weeks

**Comment by apollo06** [comment]
Issues solved, change data=payload to json=payload

**Comment by lisaam** [comment]
Ah, good to hear you figured it out
