### ISSUE TITLE
USAspending.gov Data Dictionary missing

### ISSUE THREAD

**Issue by ww2466** [fedspendingtransparency/usaspending-api#1218]
Hello, the data dictionary [link ](https://spending-api.us/docs/data-dictionary)doesn't work. Does anyone have a copy? Thanks! Andrea

**Comment by apollo06** [comment]
http://fedspendingtransparency.github.io/DAIMS-v1.2/

**Comment by tony-sappe** [comment]
@ww2466 Hello Andrea. Please see our new [Data Dictionary](https://www.usaspending.gov/#/download_center/data_dictionary) page!
