### ISSUE TITLE
API endpoints not working

### ISSUE THREAD

**Issue by charles0917** [fedspendingtransparency/usaspending-api#1322]
Hi,
I've tried several of the request examples for the API endpoints but a lot of the don't work.
For example,
/api/v2/bulk_download/list_monthly_files/ gives 
400 Bad Request
/api/v2/search/spending_by_geography/ gives
500 Internal Server Error

I'm sending POST requests through Python. Is this an issue with the server or my end?

Thanks

**Comment by jqnatividad** [comment]
Can confirm that the API endpoints were not working for me as well, that's why I ended up downloading the database snapshot and opened #1320

**Comment by lisaam** [comment]
Hi Guys,

Sorry for the delay. Are you still having problems with the endpoints? If so are the details of your request parameters?

**Comment by kenchandev** [comment]
I can confirm that the POST endpoints work via cURL.

```bash
$ curl --request POST --url https://api.usaspending.gov/api/v2/download/accounts --header "Content-Type: application/json" --data '{"account_level": "treasury_account", "filters": { "submission_type": "account_balances", "fy": "2017", "quarter": "3" }, "file_format": "csv"}' | jq '.url' | xargs wget
```

<img src="https://www.dropbox.com/s/5zwsxewrab2b4fp/Screenshot%202018-09-09%2023.02.35.png?raw=1" />

```bash
$ curl --request POST --url https://api.usaspending.gov/api/v2/search/spending_by_geography --header "Content-Type: application/json" --data '{ "scope": "place_of_performance", "geo_layer": "state", "filters": { "recipient_locations": [{ "country": "ABC" }] } }'
```

<img src="https://www.dropbox.com/s/i4w4t1fczrga1jm/Screenshot%202018-09-09%2023.02.46.png?raw=1" />

Maybe incorrect options were provided?

The [documentation](https://api.usaspending.gov/docs/endpoints) is somewhat lacking as it doesn't detail what data to send as the payload for the POST request (along with request headers). I was able to successfully make these requests due to looking at the testing suite (i.e.: https://github.com/fedspendingtransparency/usaspending-api/blob/dev/usaspending_api/search/tests/test_spending_by_geography.py#L12), which I found to be quite useful.

**Comment by lisaam** [comment]
Thanks for sharing the info @kenchandev

**Comment by mhkeller** [comment]
Trying out the `api/v2/search/spending_by_award` endpoint, the example in the docs does not work.

I am taking the data in the "request" example on this page: https://github.com/fedspendingtransparency/usaspending-api/blob/stg/usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_award.md

And putting it into the sample here: https://api.usaspending.gov/api/v2/search/spending_by_award/

Initially I get invalid type: 

![screen shot 2018-09-13 at 2 04 28 pm](https://user-images.githubusercontent.com/498744/45506670-f5e3f900-b75d-11e8-96f3-5bf0896a4e05.png)

So I put award ids in quotes like so `"award_ids": ["1018950"]`.

Then I get `"detail": "Field 'filters|legal_entities' value '779928' is above max '5000'"`

![screen shot 2018-09-13 at 2 05 29 pm](https://user-images.githubusercontent.com/498744/45506729-1ca22f80-b75e-11e8-8a40-75ba4458e51b.png)

So I remove that field and get the following error:

![screen shot 2018-09-13 at 2 06 27 pm](https://user-images.githubusercontent.com/498744/45506760-3774a400-b75e-11e8-84e7-15d3268ac495.png)

Then I gave up. I'm just trying to test this endpoint. From the documentation it's not clear which of these fields are required. When I remove all filter fields it says that `award_type_codes` is required. A request of

```json
{
    "filters": {
        "award_type_codes": ["10"],
        "award_ids": ["1018950"]
    },
    "subawards": false,
    "fields": ["Award ID", "Recipient Name", "Start Date", "End Date", "Award Amount", "Awarding Agency", "Awarding Sub Agency", "Award Type", "Funding Agency", "Funding Sub Agency"],
    "sort": "Recipient Name",
    "order": "desc"
}
```

Gives me no results:

![screen shot 2018-09-13 at 2 08 05 pm](https://user-images.githubusercontent.com/498744/45506841-73a80480-b75e-11e8-8900-29e848f43ae0.png)

**Comment by jeff-tilton** [comment]
Has this issue been resolved?  I have been testing many endpoints, mostly just copying and pasting the body straight from the documentation and it doesn't work the majority of the time.  I also went and downloaded the bulk award data in a csv with my inspect network tab open.   I see the URL and the Request payload for a successful post.  I copy those exact values and try to send a post and always get a 500 error.

```python
import requests
url = "https://api.usaspending.gov/api/v2/bulk_download/awards/"

data={"filters":{"prime_award_types":["A","B","C","D","IDV_A","IDV_B","IDV_B_A","IDV_B_B","IDV_B_C","IDV_C","IDV_D","IDV_E","02","03","04","05","10","06","07","08","09","11"],"sub_award_types":["procurement","grant"],"date_type":"action_date","date_range":{"start_date":"2021-01-01","end_date":"2021-03-01"},"def_codes":[],"recipient_locations":[{"country":"USA"}],"agencies":[{"type":"awarding","tier":"toptier","name":"Department of Agriculture"}]},"columns":[],"file_format":"csv"}

requests.post(url=url,data=data)

<Response [500]>
```

Yet this works in my browser.  I have also tested many other endpoints with varying success, as I said just copying and pasting the payload from the documentation.  Am I missing something?  Thanks
