### ISSUE TITLE
Breadth of the API

### ISSUE THREAD

**Issue by craigeddy** [fedspendingtransparency/usaspending-api#1552]
Curious what data APIs are available to get at the information found on a page such as https://www.usaspending.gov/#/award/9778360. We have a need in our app (for a USG agency) to search by award number and retrieve information such as the Recipient, Period of Performance, and contract types.

I've looked through https://api.usaspending.gov/docs/endpoints and the list doesn't seem to show what we're looking for (note that we don't want to download a ZIP file, but would rather be querying directly as the search on USASpending.gov seems to be doing.

Thanks a bunch!

**Comment by lisaam** [comment]
Hello Craig,

To pull non-zipped award data as in the USAspending.gov Advanced Search, use the same API call as the website: https://api.usaspending.gov/api/v2/search/spending_by_award/ 
Documentation for this endpoint is here: https://github.com/fedspendingtransparency/usaspending-api/blob/stg/usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_award.md 

To get the raw JSON results, you will need to send a POST request on this call with an API testing platform, such as Postman.  This call does not accept GET requests.
Here is a sample POST request body based on your example:
{
  "filters":{
"time_period": [{"start_date": "2007-10-01", "end_date": "2018-09-30"}], 
"award_ids":["AIDOAATO1500009"], 
"award_type_codes":["A", "B", "C", "D"]
},
"limit":60,
"fields":["Award ID", "Recipient Name", "Start Date", "End Date", "Award Amount", "Awarding Agency", "Awarding Sub Agency", "Contract Award Type"],
"order":"desc",
"page":1,
"sort":"Award Amount",
"subawards":false
}

The sample request body returns the following JSON result:
{
    "limit": 60,
    "results": [
        {
            "Awarding Sub Agency": "Agency for International Development",
            "Awarding Agency": "Agency for International Development",
            "Recipient Name": "CHEMONICS INTERNATIONAL, INC.",
            "Award Amount": 807295316.7,
            "Contract Award Type": "DELIVERY ORDER",
            "Start Date": "2015-04-20",
            "Award ID": "AIDOAATO1500009",
            "internal_id": 9778360,
            "End Date": "2020-11-28"
        }
    ],
    "page_metadata": {
        "hasNext": false,
        "page": 1
    }
}
Parameters may be added to or subtracted from the “filters” and “fields” sets.  Parameter options are listed in the documentation under “Fields”, and include options for Recipient and Performance data.

**Comment by craigeddy** [comment]
Thanks so much for the quick response!
