### ISSUE TITLE
Subawards failing file generation for /api/v2/bulk_download/awards/

### ISSUE THREAD

**Issue by seraphx2** [fedspendingtransparency/usaspending-api#1645]
I am specifying the following call and it looks like the file generation will work:
![image](https://user-images.githubusercontent.com/11561820/49908699-ccfcfe00-fe49-11e8-9cc3-75ed1424f7ee.png)

```
{
    "award_levels": ["sub_awards"],
    "filters": {
        "keyword": "110483521"
    },
    "columns": [],
    "file_format": "csv"
}
```

However, once I go to check the file generation, I end up with this error:
![image](https://user-images.githubusercontent.com/11561820/49908722-e0a86480-fe49-11e8-92fb-1facee564141.png)

I'm assuming this is a bug? Or is there something else causing this?

Thanks :)

**Comment by lisaam** [comment]
Hello seraphx2,

Yes, this is a bug.  It looks like recent updates to the sub-award structure in the database changed the location of the record uniqueness markers, and the /v2/bulk_download/awards/ endpoint doesn't yet have the updated pointers.

We passed this on to our API development team; the bug is at  https://federal-spending-transparency.atlassian.net/browse/DEV-2023

Thank you for reporting this!

**Comment by seraphx2** [comment]
No problem

So I'm curious. How long does it generally take for bugs to get fixed? How will I know they are done and usable?

**Comment by lisaam** [comment]
We are using Agile Scrum, so how long to fix depends on the severity/impact, capacity, and priority against other work. The best way to know when it is fixed is to follow the progress at https://federal-spending-transparency.atlassian.net/browse/DEV-2023

**Comment by Sergiobaptista2008** [comment]
250.000,00

**Comment by timxymo** [comment]
@seraphx2 curious what language/tool do you use in the screenshot? I'm fairly new to API and was hoping to duplicate some of the results in Python using requests and json package but had no luck. Also tried just doing it from the endpoint webpage but the link is taking forever, idk if I did something wrong or not.

**Comment by seraphx2** [comment]
@timxymo that is an application called Postman for quickly testing API endpoints.

**Comment by timxymo** [comment]
@seraphx2 thank you so much, it works wonder!

**Comment by tony-sappe** [comment]
@seraphx2 This issue has been resolved. Please try using the endpoint as described to generate download files.
