### ISSUE TITLE
Field mismatches between bulk-download/awards and download/awards

### ISSUE THREAD

**Issue by seraphx2** [fedspendingtransparency/usaspending-api#1648]
The fields that are returned from `bulk_download/awards` vs `download/awards` is a little different when it comes to the monetary fields:
![image](https://user-images.githubusercontent.com/11561820/49944081-8ba33780-feb7-11e8-97b6-96a221d797ec.png)

A full list of fields in bulk_download but not in download is:
*(I marked in bold the ones i think are most important, italics is secondary and normal is stuff that looks like fields that have to do with row status)*

### Contracts
*modification_number
transaction_number
parent_award_modification_number*
**total_dollars_obligated
base_and_exercised_options_value
base_and_all_options_value**
action_date
action_type_code
action_type
**price_evaluation_adjustment_preference_percent_difference**
undefinitized_action_code
undefinitized_action

*These two fields reference obligations but I am assuming they are technically different values?*
federal_action_obligation | obligated_amount 

### Assistance
*(The missing fileds here seem a little more inconsequential, but I figured I would list them out anyway)*
modification_number
action_date
correction_delete_indicator_code
correction_delete_indicator_description
action_type_code
action_type_description

*These two fields reference obligations but I am assuming they are technically different values?*
federal_action_obligation | obligated_amount 

Is there anyway to get those other fields in the download/award endpoint like they are in the bulk_download/award?
Is this a bug or intended behavior?

**Comment by lisaam** [comment]
Hello seraphx2,

The v2/bulk_download/awards/ endpoint generates a transaction-level file, while the v2/download/awards/ endpoint generates an award-level file.  Since the award-level rolls up the transactions into awards, the file is less granular and does not include the transaction-specific fields.

For the equivalent to v2/bulk_download/awards/, please use v2/download/transactions/.

**Comment by seraphx2** [comment]
awesome  thank you so much.
