### ISSUE TITLE
Bad data population

### ISSUE THREAD

**Issue by seraphx2** [fedspendingtransparency/usaspending-api#1665]
I have provided a file that has a bad record.
Row 33 is entirely messed up and missing many fields at the beginning of the record, throwing everything off and breaking my processes.

[all_contracts_prime_awards_1.zip](https://github.com/fedspendingtransparency/usaspending-api/files/2800235/all_contracts_prime_awards_1.zip)

**Comment by lisaam** [comment]
Please try to pull your data again. What you're describing sometimes happens when we update the materialized views. It resolves when that process is finished.

**Comment by seraphx2** [comment]
Ok. thanks. what I did was just continue processing records and ignore errors when the CSV data couldn't convert into my structures. but thanks for the info.
