### ISSUE TITLE
Contract Summary title not updating

### ISSUE THREAD

**Issue by BrianZito** [fedspendingtransparency/usaspending-api#1729]
After performing an advanced search for awards and opening the "Contract Summary" page for one award, then returning to the advanced search page via navigation bar and searching for a different award, the contract Summary Page showed the description field of the old award but all the other values of the new one.

**Comment by plooksm** [comment]
This is a known issue - DEV-1964

**Comment by lisaam** [comment]
This is a known issue, documented by our technical team at https://federal-spending-transparency.atlassian.net/browse/DEV-1964

Fortunately, there is an easy work-around for this issue; once the contract summary page has loaded, click your browser's 'refresh' button to pull the correct award description.

**Comment by tony-sappe** [comment]
This is not an API issue. Closing issue
