### ISSUE TITLE
500 error on spending endpoint

### ISSUE THREAD

**Issue by ece-jacob-scott** [fedspendingtransparency/usaspending-api#1890]
Hi, thank you for making this api the idea is amazing!

I'm currently just messing around with the endpoints and get an internal server error whenever I try and access the `/spending` endpoint. Regardless of the `type` specified.

![postman screenshot](https://user-images.githubusercontent.com/36082020/60199878-803bac00-980a-11e9-929f-109f91a0a7e9.png)

The only header that was set was for "Content-Type". I read the documentation again and I think I'm making the request correctly, if you think I am making an incorrect request please tell me where I'm going wrong.

Thank you!

**Comment by lisaam** [comment]
The documentation needs to be updated to better reflect when filters are required, like with budget_function

Parameters like this work: {"type":"budget_function","filters":{"fy":"2019","quarter":"2"}}

**Comment by ece-jacob-scott** [comment]
Okay that worked. Thank you! Why does it give me a 500 error though? That's kind of misleading it should be a 400 error since it's a client error. If I have time I will work on a merge request for this. Thank you again for a quick response.
