### ISSUE TITLE
Recipient/Business Type Wiki link is not public.

### ISSUE THREAD

**Issue by nhinze** [fedspendingtransparency/usaspending-api#1929]
The following link to the Recipient/Business Types returns "You do not have permission to update this wiki."

https://github.com/fedspendingtransparency/usaspending-api/wiki/Recipient-Business-Types

The incorrect link is located at:

https://github.com/fedspendingtransparency/usaspending-api/blob/master/usaspending_api/api_docs/api_documentation/search_filters.md#recipientbusiness-type

**Comment by BrianZito** [comment]
Thank you for another contribution. Documentation in the wiki was outdated for some time, and is currently being refactored.

**Comment by BrianZito** [comment]
Addressed with https://github.com/fedspendingtransparency/usaspending-api/pull/1934
