### ISSUE TITLE
Internal server error?

### ISSUE THREAD

**Issue by lhux** [fedspendingtransparency/usaspending-api#2004]
Whenever I try to a post request with the API, I keep getting a 500 internal server error? Anyone else having the same issue?

**Comment by BrianZito** [comment]
500 errors are always worth looking into, but we're gonna need more info than that. What URL were you trying to post to? What was the request body?

**Comment by lhux** [comment]
I was using /api/v2/download/awards and the request example that was linked to that endpoint in the documentation

**Comment by BrianZito** [comment]
And this issue is consistent for you? I was able to get results with 
```{
    "filters": {"time_period": [
        {
            "start_date": "2001-01-01",
            "end_date": "2001-01-31"
        }
    ]},
    "columns": [
        "award_type",
        "awarding_agency_code"
    ]
}```
a few times in a row now, although the downloads are taking a while to pack.

**Comment by lhux** [comment]
Yes, I just put this into the url version of the API and I got another "Server Error (500)"

**Comment by lisaam** [comment]
hi, this is a known issue

**Comment by BrianZito** [comment]
I was just able to replicate by using the documentation page itself instead of an external tool.

**Comment by lisaam** [comment]
Documented here https://federal-spending-transparency.atlassian.net/browse/DEV-3166

**Comment by lhux** [comment]
Great, thank you! If you know of any workarounds for using this endpoint, please let me know

**Comment by BrianZito** [comment]
It looks like the issue is just with the documentation page, not the endpoint. Calling the endpoint vi a simple Javascript application or a tool like Postman should let you keep doing whatever you're doing.

**Comment by lhux** [comment]
Should I be able to call it from Python? Because I keep getting a "500 Internal Error" message as well

**Comment by BrianZito** [comment]
You should. I would suggest making sure you are using https, with application/json as your Content-Type.

**Comment by lisaam** [comment]
It also works making the call from an app like Postman

**Comment by lhux** [comment]
```
import requests
s = requests.Session()
payload = {
    "filters": {"time_period": [
        {
            "start_date": "2001-01-01",
            "end_date": "2001-01-31"
        }
    ]},
    "columns": [
        "award_type",
        "awarding_agency_code"
    ]
}
r = s.post("https://api.usaspending.gov/api/v2/download/awards/", data=payload)
r.reason
print(r.status_code, r.reason)
```

Using this code, I get the error message "500 Internal Server Error". Do you have any suggestions?

**Comment by tony-sappe** [comment]
@lhux The issue is caused when column names are provided in the request array.
If you pass an empty list, the endpoint will function.

The bug is documented here: [DEV-2998](https://federal-spending-transparency.atlassian.net/browse/DEV-2998)
