### ISSUE TITLE
What are the list of filters for api/v1/awards?

### ISSUE THREAD

**Issue by lhux** [fedspendingtransparency/usaspending-api#2005]
More specifically, I am trying to filter by DUNS number and fiscal year. What are the filter names for this?

**Comment by BrianZito** [comment]
First things first, is there specific functionality from v1 that you need to be using? https://github.com/fedspendingtransparency/usaspending-api/blob/master/usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_award.md is the equivalent in v2, which is better documented and actively supported. You can check the link to the filter object to find DUNS and fiscal year.

**Comment by lhux** [comment]
Yes, I wasn't able to get my code to function under v2, only v1.

**Comment by BrianZito** [comment]
Is this because of the 500 error in the issue before this? If you're seeing the problem between versions that will be valuable to add to our DEV ticket and resolve the problem faster. My assumption is that some kind of data formatting/quality check was added between versions and wasn't documented correctly.

**Comment by lhux** [comment]
Yes, I get an internal server error when using v2. I also tried using recipient_unique_id as a filter and it doesn't appear to work with v1.

**Comment by lisaam** [comment]
Have you tried using the Advanced Search on USAspending.gov to form your query string? (Or just download the info you need?)

**Comment by lhux** [comment]
Is there a way to get the query code from the Advanced Search tool on the gov site?

**Comment by BrianZito** [comment]
Anytime you're on a website and it sends out a request, you can look at what was sent. It's a very powerful tool in a developer's utility belt https://www.google.com/search?ei=ezlpXcDzEcTQ-gT77Z_gDg&q=network+tab+chrome&oq=network+tab+on+browsers&gs_l=psy-ab.1.0.0i71l8.0.0..10624...0.2..0.0.0.......0......gws-wiz.Dj4ZWxXdkYU

**Comment by lhux** [comment]
I can't find the necessary information that way.

**Comment by lisaam** [comment]
I'll have an example for you in a few minutes.

**Comment by lisaam** [comment]
I searched on FY 2019 and DUNS 152670030

The Chrome screen where I pulled the query from looks like:
![Advance_Search_API](https://user-images.githubusercontent.com/16667780/64032562-ba7e3e00-cb18-11e9-8fb0-07b7933bd2eb.GIF)

Te query string is:

 {"filters":{"time_period":[{"start_date":"2018-10-01","end_date":"2019-09-30"}],"award_type_codes":["A","B","C","D"],"recipient_search_text":["152670030"]},"fields":["Award ID","Recipient Name","Start Date","End Date","Award Amount","Awarding Agency","Awarding Sub Agency","Contract Award Type"],"page":1,"limit":60,"sort":"Award Amount","order":"desc","subawards":false}

Documentation for the API endpoint is at:
https://github.com/fedspendingtransparency/usaspending-api/blob/master/usaspending_api/api_docs/api_documentation/advanced_award_search/spending_by_award.md

I hope this helps.

**Comment by lhux** [comment]
<img width="361" alt="Capture" src="https://user-images.githubusercontent.com/53314330/64033177-e9e17a80-cb19-11e9-8ce1-d02264e3a5b0.PNG">
Do you have any suggestions?

**Comment by lisaam** [comment]
It looks like you may be missing some json details. Try this:

import requests

json_body = {
    "filters": {"time_period": [
        {
            "start_date": "2018-10-01",
            "end_date": "2019-09-30"
        }],
        "award_type_codes": ["A","B","C","D"],
        "recipient_search_text": ["152670030"]
    },
    "fields": ["Award ID", "Recipient Name", "Start Date", "End Date", "Award Amount", "Awarding Agency", "Awarding Sub Agency","Contract Award Type"],
    "page": 1,
    "limit": 60,
    "sort": "Award Amount",
    "order": "desc",
    "subawards":"false"
}
r = requests.post('https://api.usaspending.gov/api/v2/search/spending_by_award', json=json_body)
print(r.status_code)
