### ISSUE TITLE
Downloading Zip Files?

### ISSUE THREAD

**Issue by lhux** [fedspendingtransparency/usaspending-api#2012]
When using "api/v2/download/awards", how do you access your zip file? I've tried putting in the generated url into my browser, but no zip file is ever generated or available for download. 

Thanks!

**Comment by BrianZito** [comment]
What's the generated url, and what download were you trying? Putting the url in the browser should be enough to get the file once the download is complete.

**Comment by lhux** [comment]
https://files.usaspending.gov/generated_downloads/all_prime_awards_subawards_20190905005515547081.zip

**Comment by lisaam** [comment]
It looks like this situation is related to:
https://federal-spending-transparency.atlassian.net/browse/DEV-2998
