### ISSUE TITLE
Getting 'Internal Server Error' with Python's requests library

### ISSUE THREAD

**Issue by johncmerfeld** [fedspendingtransparency/usaspending-api#2061]
Hello,

I've tried several examples of POST requests using the documentation and am only receiving 500 errors. Not sure if this is related to other issues.
Code:
```
import requests 

url_base = 'https://api.usaspending.gov'
endpoint = '/api/v2/download/awards/'

filter_object = {
    "filters": {"time_period": [
        {
            "start_date": "2001-01-01",
            "end_date": "2001-01-31"
        }
    ]},
    "columns": [
        "award_type",
        "awarding_agency_code"
    ]
}

request_url = url_base + endpoint
response = requests.post(request_url, data = filter_object)

response.reason
# Out[62]: 'Internal Server Error'
```

I've tried with other endpoints and filter objects, but POST requests always return with a 500.

**Comment by lisaam** [comment]
Hi John,
Where are you running the POST request? On the USAspending.gov page or in a different tool?

**Comment by johncmerfeld** [comment]
Sorry, I should have been more clear: I'm running it on my local machine with Python 3.

**Comment by lisaam** [comment]
There is an issue with downloads accepting specified columns that results in a 500 error. It is currently being addressed as part of https://federal-spending-transparency.atlassian.net/browse/DEV-2998

**Comment by johncmerfeld** [comment]
I saw that, but I'm not sure it's the same thing. I get it even if I don't specify any columns. I can't get any POST request to return.
```
filter_object = {
    "filters": {"time_period": [
        {
            "start_date": "2001-01-01",
            "end_date": "2001-01-31"
        }
    ]}
}
```

**Comment by lisaam** [comment]
Ok, let us look at it some more

**Comment by sethstoudenmier** [comment]
Hey John,
I have copied and edited what you pasted above. This should work for you as long as you don't specify columns. As Lisa said, the ability to specify columns is currently being addressed.
```
import requests
import json

url_base = 'https://api.usaspending.gov'
endpoint = '/api/v2/download/awards/'

filter_object = {
    "filters": {"time_period": [
        {
            "start_date": "2001-01-01",
            "end_date": "2001-01-31"
        }
    ]}
}

request_url = url_base + endpoint

# Need to specify the header type
headers = {"Content-type": "application/json"}

# Need to specify the data that you pass as a JSON string
data = json.dumps(filter_object)

response = requests.post(request_url, headers=headers, data=data)
```

**Comment by dannellyz** [comment]
I am receiving this same error when using the `/api/v2/search/spending_by_award/` endpoint. Is this due to the `fields` feature? 

...Full Code...
`params = {
    "filters": {
        "award_type_codes": ["10"],
        "award_ids": ["1018950"]
    },
    "subawards": "False",
    "fields": [
          "Award ID",
          "Recipient Name",
          "Start Date",
          "End Date",
          "Award Amount",
          "Awarding Agency",
          "Awarding Sub Agency",
          "Contract Award Type",
          "Award Type",
          "Funding Agency",
          "Funding Sub Agency"],
    "sort": "Recipient Name",
    "order": "desc"
}
url = "https://api.usaspending.gov/api/v2/search/spending_by_award/"
r = requests.post(url, data=params)
print(r.status_code, r.reason)
"HTTPError: 500 Server Error: Internal Server Error for url: https://api.usaspending.gov/api/v2/search/spending_by_award/"`

**Comment by sethstoudenmier** [comment]
@dannellyz make sure that you convert your dictionary of data to be a JSON string with something such as `data = json.dumps(params)` and also specify the header type. Both of those are shown in the code above your comment. You should be able to edit that to fit your needs.
