### ISSUE TITLE
bulk_download POST request results in missing "filters"

### ISSUE THREAD

**Issue by prdctofchem** [fedspendingtransparency/usaspending-api#2191]
When trying to make a POST request (via Python requests package) to the "/api/v2/bulk_download/awards/" endpoint, I get the response,
"{'detail': 'Missing one or more required body parameters: filters'}". I am trying to get bulk data on awards for 2019. Below is my actual request:

```
host_url = 'https://api.usaspending.gov'
endpoint = "/api/v2/bulk_download/awards/"
payload = {
    "filters": {
        "agency": "all",
        "award_types": [
            "contracts", 
            "direct_payments", 
            "grants", 
            "idvs", 
            "loans", 
            "other_financial_assistance"
        ],
        "date_range": {
            "start_date": "2019-01-01", 
            "end_date": "2019-12-01"
        },
        "date_type": "action_date"
    },
    "award_levels": ["prime_awards", "sub_awards"]
}
response = requests.post(host_url+endpoint, params = payload)
```
I've even tried pasting in the Body example from the Bulk Award Download page
[(https://github.com/fedspendingtransparency/usaspending-api/blob/master/usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md)] with the same result. Any help is appreciated.

-R

**Comment by tony-sappe** [comment]
@prdctofchem It appears the request code is incorrect.

When using Postman and our [online API docs](https://api.usaspending.gov/api/v2/bulk_download/awards/) the request was successful and started running.

Issue #2061 might contain helpful tips:
https://github.com/fedspendingtransparency/usaspending-api/issues/2061#issuecomment-537565181

**Comment by prdctofchem** [comment]
I see, I was missing a header specification and the parameters-dictionary needs to be json. Thanks for the reference. Is there any documentation on headers for various endpoints, or is the one to which you you linked the only one I will need?
Thanks.

**Comment by tony-sappe** [comment]
It wouldn't be a bad idea to resurrect introductory tutorials, recipes, or a Postman collection which would be helpful to get started. For now, all of the USAspending API endpoints return JSON, and all of the POSTs need to specify the content-type application/JSON header. This is common for POST methods in RESTful APIs.

https://api.usaspending.gov/api/v2/recipient/duns/ is a simple endpoint to help provide details of a working POST (click the POST button to see the JSON response and the response headers, no body required).

Additionally, many browsers have some kind of "developer tools" panel to inspect the API calls. The tools would show the request url, headers, and body along with the response headers and body.

**Comment by prdctofchem** [comment]
I appreciate the explanation. As for the bulk download, the custom link https://files.usaspending.gov/generated_downloads/all_prime_transactions_subawards_20191230232622354250.zip still opens a page that says "Your file is still in the works. Use your custom link to grab it later," though the status of the response is 'ready'.

**Comment by tony-sappe** [comment]
That is definitely confusing. "Ready" is actually the first status of the process ("ready for processing", not "ready for downloading")

There have been improvements to the download API behavior and additionally if you click the above download file link you will see an accurate message reporting the error.
