### ISSUE TITLE
/spending_by_award/ 200 but empty reaults

### ISSUE THREAD

**Issue by montybean** [fedspendingtransparency/usaspending-api#2313]
I did a successful query on 2/5, but when I tried again on 2/25, I received an empty results back. 
My code has not changed. Here is the JSON I'm sending. Please advise.

>{
  "filters": {
    "time_period": [
      {
        "start_date": "2012-10-01",
        "end_date": "2019-09-30"
      }
    ],
    "award_type_codes": [
      "A",
      "B",
      "C",
      "D"
    ],
    "recipient_search_text": [
      "freedom"
    ],
    "agencies": [
      {
        "type": "awarding",
        "tier": "toptier",
        "name": "All"
      }
    ]
  },
  "fields": [
    "Award ID",
    "Recipient Name",
    "Start Date",
    "End Date",
    "Award Amount",
    "Awarding Agency",
    "Awarding Sub Agency",
    "Contract Award Type"
  ],
  "page": 1,
  "limit": 60,
  "sort": "Award Amount",
  "order": "desc"
}

>

**Comment by kbard** [comment]
```
"agencies": [
    {
        "type": "awarding",
        "tier": "toptier",
        "name": "All"
    }
]
```
Is searching for an awarding agency with the name "All".  There is no such agency.  To search across all agencies, remove this section altogether.

**Comment by montybean** [comment]
Brilliant!
Thank you for catching it so quickly. Yes, I forgot that I added "All" option for the users but didn't update my search code. 
I modified it and it works now.
