### ISSUE TITLE
Ability to get prime_award_types list

### ISSUE THREAD

**Issue by raphaelseo** [fedspendingtransparency/usaspending-api#2369]
Are there any way to get prime award types list from API or anywhere? I think I can see all values from github page. https://github.com/fedspendingtransparency/usaspending-api/blob/master/usaspending_api/api_contracts/contracts/v2/bulk_download/awards.md

But I would like to get these values from API to avoid hardcode. 

Otherwise, how can I send request to `/api/v2/bulk_download/awards/` for all prime award types without specifying all values like the example.
```
{
      "filters": {
          "agency": 50,
          "prime_award_types": "all",
          "sub_award_types": ["procurement"],
          "date_range": {
              "start_date": "2019-01-01",
              "end_date": "2019-12-31"
          },
          "date_type": "action_date"
      }
  }
```

**Comment by BrianZito** [comment]
Currently we don't have a reference endpoint for the categories of award types, but I just made https://federal-spending-transparency.atlassian.net/browse/DEV-4775 and added it to our backlog for possible prioritization. 

If you're willing to work with a hackish solution, this list does appear as an error message for other endpoints that can't support multiple categories. For example, calling `/api/v2/search/spending_by_award/`
With a json body of:
```
{
  "filters": {
    "time_period": [
      {
        "start_date": "2007-10-01",
        "end_date": "2024-09-30"
      }
    ],
    "award_type_codes": [
      "A",
      "02",
      "C",
      "D"
    ],
    "naics_codes": {
    	"require": ["33", "3333333"],
    	"exclude": ["3333"]
    }
  },
  "fields": [
    "Award ID",
    "Recipient Name",
    "Start Date",
    "End Date",
    "Award Amount",
    "Awarding Agency"
  ],
  "page": 1,
  "limit": 60,
  "sort": "Award Amount",
  "order": "desc",
  "subawards": false
}
```
will give you an `award_type_groups` object that you can work off of programatically. Obviously, as an error message, we can't guarantee this behavior in the long term.

**Comment by BrianZito** [comment]
If it helps, note that these types do not change very often, if at all.

**Comment by raphaelseo** [comment]
@BrianZito Thank you. How can I get noticed if you create reference endpoint?

**Comment by BrianZito** [comment]
My pleasure. We don't have any means of pushing notifications to you directly, but we have [regular releases](https://github.com/fedspendingtransparency/usaspending-api/releases/tag/2020-03-09) and [records on the wiki](https://github.com/fedspendingtransparency/usaspending-website/wiki#march-09-2020) for new features. Github's Watch feature will let you be notified every time this happens.

**Comment by raphaelseo** [comment]
Thank you.
