### ISSUE TITLE
Spending by Category Doesn't Filter

### ISSUE THREAD

**Issue by trevinatan** [fedspendingtransparency/usaspending-api#2372]
The Spending by Category endpoint does not work as intended; when I filter by counties in one particular state, the endpoint returns numerous pages of counties that are not in that state.

Sample request below:

`{
            "category": "county",
            "filters": {
                "recipient_locations": [{"country": "USA", "state": "CA"}]
            },
            "limit": 10,
            "page": 20
        }`

None of these returned counties are actually located in California.
This is a persistent issue with all other states. Even if you put in Delaware as the location filter, which has 3 counties, the API will return hundreds.

**Comment by tony-sappe** [comment]
Hello @trevinatan, thank you for the question. There are two location filters for the "search" API endpoints: Recipient Location and Primary Place of Performance (PPoP). Spending By Category is actually providing PPoP location data, so for the filter and the response to match the request should use `place_of_performance_locations`.

```json
{
    "category": "county",
    "filters": {
        "place_of_performance_locations": [
            {
                "country": "USA",
                "state": "CA"
            }
        ]
    },
    "limit": 10,
    "page": 20
}

```

**Comment by trevinatan** [comment]
@tony-sappe Thanks so much! That's exactly what I was looking for.
