### ISSUE TITLE
api/v2/bulk_download/awards/ is no longer downloading... is there a config change?

### ISSUE THREAD

**Issue by makretch** [fedspendingtransparency/usaspending-api#3017]
I used this endpoint just yesterday and several times this past week, and it downloaded the desired CSV as intended. However, the endpoint didn't seem to function today. My code didn't change, other than modifying `end_date`, as usual. Here are the details to replicate the glitch:

### My Payload:
```
{
      "filters": {
          "prime_award_types": [
              "A",
              "B",
              "C",
              "D",
              "IDV_A",
              "IDV_B",
              "IDV_B_A",
              "IDV_B_B",
              "IDV_B_C",
              "IDV_C",
              "IDV_D",
              "IDV_E",
              "02",
              "03",
              "04",
              "05",
              "10",
              "06",
              "07",
              "08",
              "09",
              "11"
          ],
          "sub_award_types": [],
          "date_type": "last_modified_date",
          "date_range": {
              "start_date": "2021-02-07",
              "end_date": "2021-03-03"
          },
          "agencies": [
              {
                  "type": "funding",
                  "tier": "subtier",
                  "name": "All"
              }
          ]
      },
      "columns": [],
      "file_format": "csv"
  }
```

Returns status URL of:
```
https://api.usaspending.gov/api/v2/download/status?file_name=All_PrimeTransactions_2021-03-03_H21M04S25045742.zip
```

### Expected result:
The status URL usually returns `{"status":"running"...}` until the download is ready, when it returns `{"status":"finished"...}`. I can then download the file: `"file_url":"https://files.usaspending.gov/generated_downloads/All_PrimeTransactions_2021-03-03_H21M04S25045742.zip"`

### Actual result:
The status URL returns:
```
{"status":"ready","message":null,"file_name":"All_PrimeTransactions_2021-03-03_H21M04S25045742.zip","file_url":"https://files.usaspending.gov/generated_downloads/All_PrimeTransactions_2021-03-03_H21M04S25045742.zip","total_size":null,"total_columns":null,"total_rows":null,"seconds_elapsed":null}
```

I noticed something already seemed off with "status".

The download never actually materializes. "Your download file is still in the works" shows in the browser but nothing actually happens (even after waiting 1 hour+).

Did the API configuration change?

**Comment by makretch** [comment]
The service seems to be working as expected this morning. Closing unless I come across further issues. Thanks!

**Comment by lisaam** [comment]
Hi, we had an issue with the APIs due to a very large data load that took over 24 hours. The APIs are now back to normal, as you discovered.

Although this is a valid way to contact us, the Community on USAspending.gov generally has a faster response time.
