### ISSUE TITLE
/api/v2/recipient/duns/ down or just unreliable?

### ISSUE THREAD

**Issue by ColtonBeery** [fedspendingtransparency/usaspending-api#3088]
I have been attempting to use /api/v2/recipient/duns/ to retrieve the unique recipient ID for a company, because that's the only call that I can see that returns it. I want to pass that to the /api/v2/search/spending_over_time/ to get some information about specific companies. 

The issue is, lately, almost every time that I attempt to call that API, that I get a response 500; _sometimes_ it goes through, but usually not. According to the documentation, 500 means that there were server-side errors. 

Is there another API call that returns this recipient ID I can use that is more reliable?

**Comment by weilandia** [comment]
Running into the same issue.

This is what it looks like when it happens through the api gui:

<img width="900" alt="Screen Shot 2021-04-14 at 4 43 15 PM" src="https://user-images.githubusercontent.com/13652979/114794444-59cd6480-9d41-11eb-91fc-5a687f54b969.png">

**Comment by lisaam** [comment]
Hi Folks,

We are working to resolve issues with the DUNS endpoints. We'll update in the when it's resolved - hopefully in the next day or two.

**Comment by ColtonBeery** [comment]
Thank you. 
I look forward to hearing back with an update soon.

**Comment by lisaam** [comment]
@ColtonBeery This issue is now resolved. The DUNS endpoints should now be available 100% of the time and no longer giving 500 on a regular basis.

**Comment by ColtonBeery** [comment]
Testing a few times, everything seems to be working fine. Thank you for resolving the issue!
