### ISSUE TITLE
Is it possible to make Award Retrieve [/api/v2/awards/{award_id}/] using award_id_fain?

### ISSUE THREAD

**Issue by oyeromenko-ebsco** [fedspendingtransparency/usaspending-api#3100]
I'm trying to view details about a specific award, using /api/v2/awards/{award_id}/  but in this case I need to know assistance_award_unique_key.    Is there any way to query awards by award_id_fain?

**Comment by lisaam** [comment]
You can send a POST request to https://api.usaspending.gov/api/v2/search/spending_by_award/

with a JSON body:

`{"filters":{"time_period":[

{"start_date":"2007-10-01","end_date":"2021-09-30"}
],"award_type_codes":["02","03","04","05"],"award_ids":["PQ10298619"]},"fields":["Award ID","Recipient Name","Start Date","End Date","Award Amount","Description","def_codes","COVID-19 Obligations","COVID-19 Outlays","Awarding Agency","Awarding Sub Agency","Award Type","recipient_id","prime_award_recipient_id"],"page":1,"limit":60,"sort":"Award Amount","order":"desc","subawards":false}`

Edit "award_ids":["PQ10298619"]}, to change the FAIN

**Comment by lisaam** [comment]
Or if you only want one award, use Advanced Search

https://www.usaspending.gov/search/?hash=f3909d8463f50b9f426fd8967106d6e0

**Comment by oyeromenko-ebsco** [comment]
Thank you, Lisa!
