### ISSUE TITLE
Is the following endpoint dead:  /api/v2/bulk_download/list_monthly_files/?

### ISSUE THREAD

**Issue by robert-roussel-ctr** [fedspendingtransparency/usaspending-api#3156]
Hello,

I tried a post request to the following endpoint:

https://api.usaspending.gov/api/v2/bulk_download/list_monthly_files/

with the following request:

{"agency": 69, "fiscal_year": 2021}

taken straight from the linked documentation here:

https://github.com/fedspendingtransparency/usaspending-api/blob/master/usaspending_api/api_contracts/contracts/v2/bulk_download/list_monthly_files.md

However, I keep getting a 400 error, telling me that the the field agency is required. But I supplied that field in the request above.

Can you tell me whether something is wrong with that api endpoint, or with the documentation that is linked? Or is something wrong with my request format that I'm not catching?

Thank you!

**Comment by lisaam** [comment]
i Robert,

The documentation specifies:

- agency (required, number) Agency database ID or all.

Although the CGAC for the Department of Transportation is 069, the database ID is 62 and the JSON request for contract data would be:

{"agency":"62","fiscal_year":2021,"type":"contracts"}

This API downloads static files that are also available at https://www.usaspending.gov/download_center/award_data_archive

**Comment by robert-roussel-ctr** [comment]
Thank you for the helpful info - where can I find a list of all the Agency database IDs for future reference?
I can't get the post to work on the site, but it is working through Python so we're all good on that end - thank you!
If you can provide a list of the db IDs, you can feel free to close the issue.

**Comment by lisaam** [comment]
Hi Robert,

You can use https://api.usaspending.gov/api/v2/bulk_download/list_agencies/  with the request body of {"type":"award_agencies"} to the list

**Comment by robert-roussel-ctr** [comment]
Thank you, this is very helpful!
