### ISSUE TITLE
Awards Endpoint returns 500 error on page 2148 - throttling?

### ISSUE THREAD

**Issue by aliciatb** [fedspendingtransparency/usaspending-api#381]
Hi, I have been hitting the Awards endpoint, https://api.usaspending.gov/api/v1/awards/ posting {"verbose": true, "limit":100} to retrieve all the data, and noticed that on page 2148, https://api.usaspending.gov/api/v1/awards/?limit=100&page=2148&req=c6e30f115d6 it returned a server 500 error. Is there any throttling that is being done that is being done that would return the error and is there anything that I can do to be able to retrieve all of the available data?

![api_awards_workflow_error](https://user-images.githubusercontent.com/3361040/26897878-da0f7e94-4b7e-11e7-8180-305e61fee5a3.png)

Thanks!

Alicia

**Comment by russellbodine** [comment]
This is an error we are seeing in production right now.  A ticket is in and being actively worked on.

**Comment by tony-sappe** [comment]
The codebase has significantly changed since this ticket was opened. @aliciatb if there is suspected throttling in the future please open another Github issue.
