### ISSUE TITLE
Error message on certain get and post requests 

### ISSUE THREAD

**Issue by danshorstein** [fedspendingtransparency/usaspending-api#395]
I'm running into a constant issue with usaspending get and post requests. Often when there's at least one parameter passed into the request, the JSON returned will just be "message": "get() returned more than one RequestCatalog -- it returned x!" replacing x with any number from 2 to 4 or so. For example this happens when I add the page to the awards endpoint url. https://api.usaspending.gov/api/v1/accounts/awards/?page=1

I did a quick google and the internet suggests it's a django server issue, and can be fixed by replacing Model.objects.get() with Model.objects.filter() - https://stackoverflow.com/a/22064255

**Comment by russellbodine** [comment]
Yep, we are seeing this on the dev side too.  It involves some of our custom caching code, but it is a top priority and being fixed in the next production release.  

For the meantime, we put a bandaid on this issue by manually resetting our cache, and we are doing it whenever we see this bug.
