### ISSUE TITLE
Full database archive only includes 1 year of subawards in subawards_search

### ISSUE THREAD

**Issue by weilandia** [fedspendingtransparency/usaspending-api#4217]
When downloading and restoring the full archive from https://files.usaspending.gov/database_download/ we found out that it only includes the past year of subawards in the subawards_search table.

Is this by design? Is there a recommended way to get all subaward history?

**Comment by aguest-kc** [comment]
The full database archive currently has all of our Subaward data included.

Currently, the `broker_created_at` and `broker_updated_at` columns do show a date of 10/14/2023. These two columns are updated whenever our Broker system reloads their Subaward data, which they did in October of 2023.

A better date field to use is the `action_date`, which shows dates back to 2007.

**Comment by weilandia** [comment]
Thanks you!
