### ISSUE TITLE
Installing for Windows

### ISSUE THREAD

**Issue by ET-SPG** [fedspendingtransparency/usaspending-api#464]
Hello, I am not very experienced with code and API setups, but I was trying to follow the readme on a windows system. I seem to have hit a roadblock when installing the packages defined by the requirements text file as it cannot install uWSGI.

I've tried to use Cygwin to get around that, but that is giving me trouble as well. Is there a way around using the uWSGI package? Has anyone successfully installed on a Windows environment that can give me some tips?

Thank you!

**Comment by tony-sappe** [comment]
Unsure if you are still trying on to install a working server on Windows @ET-SPG, but we don't have any firsthand experience running the production system on Windows. Were you able to run a test server using Django's management command (`python manage.py runserver`) on your system?

Another idea would be to run the production server in a virtual machine or Docker container.

**Comment by tony-sappe** [comment]
There is a functional docker compose file in the root of the repo [here](https://github.com/fedspendingtransparency/usaspending-api/blob/master/docker-compose.yaml). This should clear up compatibility issues between Windows, Linux, and Mac
